SHOW PARAMETER SPFILE;
SELECT name, value FROM v$parameter WHERE name IN ('spfile', 'pfile');

CREATE PFILE='D:\stady\oracle\lab6\KVI_PFILE.ORA' FROM SPFILE;
CREATE SPFILE FROM PFILE='D:\stady\oracle\lab6\KVI_PFILE.ORA';

SHUTDOWN IMMEDIATE; STARTUP;

SELECT NAME FROM V$CONTROLFILE;

ALTER DATABASE BACKUP CONTROLFILE TO TRACE AS 'D:\STADY\ORACLE\ORADATA\ORCL\CONTROL03.CTL';

SHOW PARAMETER REMOTE_LOGIN_PASSWORDFILE;

SELECT * FROM V$DIAG_INFO;

SHOW PARAMETER DIAGNOSTIC_DEST;
SHOW PARAMETER USER_DUMP_DEST;

