SELECT tablespace_name, contents FROM dba_tablespaces;

SELECT file_name, tablespace_name
FROM dba_data_files
UNION ALL
SELECT file_name, tablespace_name
FROM dba_temp_files;

SELECT group#, sequence#, status FROM v$log;

SELECT member, group# FROM v$logfile;

ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM v$log;

ALTER DATABASE ADD LOGFILE GROUP 4 'D:\stady\oracle\LAB4\GROUP4.LOG' SIZE 50M BLOCKSIZE 512;
ALTER DATABASE ADD LOGFILE MEMBER 'D:\stady\oracle\LAB4\FILE4.LOG' TO GROUP 4
SELECT * FROM v$log;
ALTER DATABASE DROP LOGFILE GROUP 4;

--SHOW PARAMETER log_archive_start;

SELECT MAX(sequence#) FROM v$archived_log;
ALTER DATABASE OPEN;
SELECT *FROM v$database;
-- ALTER DATABASE CLOSE;
-- ALTER DATABASE DISMOUNT;
-- ALTER DATABASE INSTANCE SHUTDOWN;
-- ALTER DATABASE STARTUP MOUNT;

ALTER DATABASE ARCHIVELOG;

ALTER SYSTEM ARCHIVE LOG CURRENT;

SELECT *FROM v$database;

ALTER DATABASE NOARCHIVELOG;
SELECT * FROM GV$CONTROLFILE;

