 CREATE TABLE KVI_t(id NUMBER(3) PRIMARY KEY,str NVARCHAR2(50));  
INSERT INTO KVI_T VALUES (1,'one');
INSERT INTO KVI_T VALUES (2,'two');
INSERT INTO KVI_T VALUES (3,'three');
 COMMIT;
 UPDATE KVI_T SET ID = 4, STR = 'four' WHERE ID = 1;
 UPDATE KVI_T SET ID = 5, STR = 'five' WHERE ID = 2;
 COMMIT;
-- SELECT * FROM KVI_T;
-- SELECT ID, STR FROM KVI_T WHERE ID >3;
BEGIN
DELETE FROM KVI_T WHERE ID = 3;
ROLLBACK;
END;

 CREATE TABLE KVI_T_chield(ID NUMBER(3) PRIMARY KEY, DATA NVARCHAR2(50),
     Parant_ID NUMBER(3), FOREIGN KEY (Parant_ID) REFERENCES KVI_T(ID) );
INSERT INTO KVI_T_chield VALUES (1,'one',3);
INSERT INTO KVI_T_chield VALUES (2,'two',4);
INSERT INTO KVI_T_chield VALUES (3,'three',5);

SELECT KVI_T_CHIELD.PARANT_ID, KVI_T.STR, KVI_T_CHIELD.ID,
 KVI_T_CHIELD."DATA" FROM KVI_T JOIN KVI_T_CHIELD ON KVI_T.ID = KVI_T_CHIELD.PARANT_ID;

SELECT KVI_T.ID, KVI_T.STR, KVI_T_CHIELD.ID AS CHILD_ID,
 KVI_T_CHIELD."DATA" FROM KVI_T LEFT OUTER JOIN KVI_T_CHIELD ON KVI_T.ID = KVI_T_CHIELD.ID;

 SELECT COUNT(*) FROM KVI_T;


DROP TABLE KVI_T_CHIELD;
DROP TABLE KVI_T;