CREATE GLOBAL TEMPORARY TABLE temp_table (id NUMBER) ON COMMIT DELETE ROWS;

INSERT INTO temp_table VALUES (1);

COMMIT; 

CREATE  SEQUENCE S1 START WITH 1000 INCREMENT BY 10 NOCACHE NOCYCLE NOORDER;
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.CURRVAL FROM DUAL;

CREATE  SEQUENCE S2 START WITH 10 INCREMENT BY 10 MAXVALUE 100 NOCYCLE;
SELECT S2.NEXTVAL FROM DUAL; 

CREATE SEQUENCE S3 START WITH 10 INCREMENT BY -10 MINVALUE -100 MAXVALUE 100  NOCYCLE ORDER;
SELECT S3.NEXTVAL FROM DUAL; 

CREATE  SEQUENCE S4 START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 5 CYCLE CACHE 4 NOORDER;

SELECT S4.NEXTVAL FROM DUAL; 

SELECT * FROM ALL_SEQUENCES;

CREATE TABLE T1 (N1 NUMBER(20), N2 NUMBER(20), N3 NUMBER(20), N4 NUMBER(20)) CACHE;
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);

CREATE CLUSTER ABC (X NUMBER(10)) SIZE 200 HASHKEYS 100;
CREATE TABLE A (XA NUMBER(10), VA VARCHAR2(12)) CLUSTER ABC (XA);
CREATE TABLE B (XB NUMBER(10), VB VARCHAR2(12)) CLUSTER ABC (XB);
CREATE TABLE C (XC NUMBER(10), VC VARCHAR2(12)) CLUSTER ABC (XC);

SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('A', 'B', 'C');
SELECT CLUSTER_NAME FROM USER_CLUSTERS WHERE CLUSTER_NAME = 'ABC';

CREATE SYNONYM syn_table_c FOR KVICORE.C;
CREATE PUBLIC SYNONYM syn_table_b FOR KVICORE.B;



CREATE TABLE g (id NUMBER PRIMARY KEY, value VARCHAR2(50));
CREATE TABLE h (id NUMBER, a_id NUMBER REFERENCES g(id), value VARCHAR2(50));
CREATE VIEW V1 AS SELECT g.id, g.value, h.value AS b_value FROM g INNER JOIN h ON g.id = h.a_id;

CREATE MATERIALIZED VIEW MV_KVI REFRESH COMPLETE START WITH SYSDATE NEXT SYSDATE + INTERVAL '2' MINUTE AS SELECT * FROM V1;

CREATE DATABASE LINK db_link CONNECT TO GDV IDENTIFIED BY "D12345" USING '172.20.10.8/SAUPDB';
INSERT INTO GDV_T1@db_link VALUES(324,'LEX');

SELECT * FROM GDV_T1@db_link;

 

