CREATE TABLE Role_Table (
  role_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Name VARCHAR2(50) UNIQUE NOT NULL
);
--DROP TABLE Role_Table;

INSERT INTO Role_table (Name) VALUES ('Администратор');
INSERT INTO Role_table (Name) VALUES ('Модератор');
INSERT INTO Role_table (Name) VALUES ('Пользователь');
INSERT INTO Role_table (Name) VALUES ('Гость');

CREATE TABLE User_table (
  User_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Login VARCHAR2(50) UNIQUE NOT NULL,
  Password VARCHAR2(255) NOT NULL,
  Email VARCHAR2(100) UNIQUE,
  Name VARCHAR2(50) NOT NULL,
  SecondName VARCHAR2(50),
  Age NUMBER(3),
  Role_Id NUMBER REFERENCES Role_Table(Role_Id)
);
--DROP TABLE User_table;

CREATE TABLE Blog (
  Blog_Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  User_Id NUMBER REFERENCES User_Table(User_Id) ON DELETE CASCADE,
  Name VARCHAR2(100) NOT NULL,
  Discription VARCHAR2(255),
  Timestamp DATE DEFAULT SYSDATE
);
--DROP TABLE Blog;

CREATE TABLE Post (
  Post_Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Blog_Id NUMBER REFERENCES Blog(Blog_Id) ON DELETE CASCADE,
  Name VARCHAR2(100) NOT NULL,
  Containing CLOB,
  Timestamp DATE DEFAULT SYSDATE,
  CountViews NUMBER DEFAULT 0
);
--DROP TABLE Post;

CREATE TABLE Comment_Table (
  Comment_Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  User_Id NUMBER REFERENCES User_Table(User_Id) ON DELETE CASCADE,
  Post_Id NUMBER REFERENCES Post(Post_Id) ON DELETE CASCADE,
  Containing CLOB,
  Timestamp DATE DEFAULT SYSDATE
);
--DROP TABLE Comment_Table;

CREATE TABLE LIKE_TABLE (
  LIKE_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  User_Id NUMBER REFERENCES User_Table(User_Id) ON DELETE CASCADE,
  Comment_Id NUMBER REFERENCES Comment_Table(Comment_Id) ON DELETE CASCADE,
  Timestamp DATE DEFAULT SYSDATE
)
--DROP TABLE LIKE_TABLE;

CREATE TABLE Favorite (
  Favorite_Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  User_Id NUMBER REFERENCES User_Table(User_Id),
  Post_Id NUMBER REFERENCES Post(Post_Id),
  Timestamp DATE DEFAULT SYSDATE
);
--DROP TABLE Favorite;

CREATE TABLE Subscription (
  Subscription_Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Subscriber_Id NUMBER REFERENCES User_Table(User_Id) ON DELETE CASCADE,
  Blog_Id NUMBER REFERENCES Blog(Blog_Id) ON DELETE CASCADE
);
--DROP TABLE Subscription;

CREATE INDEX idx_post_blogid ON Post(Blog_Id);
CREATE INDEX idx_comment_postid ON Comment_Table(Post_Id);
CREATE INDEX post_text_index ON Post(Containing) INDEXTYPE IS ctxsys.context; -- FullTextSearch
CREATE INDEX post_name_index ON Post(Name) INDEXTYPE IS ctxsys.context; -- FullTextSearch

CREATE UNIQUE INDEX unique_subscription ON SUBSCRIPTION(subscriber_Id, blog_Id);
CREATE UNIQUE INDEX unique_favorite ON Favorite(User_Id, Post_Id);
CREATE UNIQUE INDEX unique_like ON Like_Table(User_Id, Comment_Id);



CREATE SEQUENCE blog_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE post_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE comment_seq START WITH 1 INCREMENT BY 1 NOCACHE;


SELECT * FROM dba_feature_usage_statistics
WHERE name LIKE 'Oracle Text';
SELECT comp_name, version, status
FROM dba_registry
WHERE comp_name LIKE '%Text%';
-- EXECUTE dbms_feature_value.enable('Oracle Text'); 

CREATE ROLE UserR;
GRANT CREATE SESSION TO UserR;
GRANT DBA to ADMIN;
SELECT role FROM dba_roles WHERE role = 'ADMIN';
SELECT * FROM dba_sys_privs WHERE grantee = 'ADMIN';

CREATE User AdminUser IDENTIFIED BY 111;
grant ADMIN to adminUser;

CREATE User ModeratorUser IDENTIFIED BY 111;
grant Moderator to ModeratorUser;

CREATE User UserUser IDENTIFIED BY 111;
grant userr to userUser;

CREATE User guestUser IDENTIFIED BY 111;
grant guest to guestUser;

GRANT CREATE SESSION,
       CREATE TABLE,
       CREATE VIEW,
       CREATE PROCEDURE,
       CREATE SEQUENCE,
      CREATE TRIGGER,
      DROP ANY TABLE,
      ALTER ANY TABLE,
      SELECT ANY TABLE,
      INSERT ANY TABLE,
      UPDATE ANY TABLE,
      DELETE ANY TABLE
TO admin;


-- GRANT CREATE SESSION,
--       SELECT ON User,
--       SELECT ON Blog,
--       SELECT ON Post,
--       SELECT ON Comment,
--       SELECT ON Favorite,
--       SELECT ON Subscription,
--       INSERT ON Comment,
--       UPDATE ON Comment,
--       DELETE ON Comment,
--       UPDATE ON Post,
--       DELETE ON Post
-- TO moderator;

-- GRANT CREATE SESSION,
--       SELECT ON User,
--       SELECT ON Blog,
--       SELECT ON Post,
--       SELECT ON Comment,
--       SELECT ON Favorite,
--       SELECT ON Subscription,
--       INSERT ON Blog,
--       INSERT ON Post,
--       INSERT ON Comment,
--       INSERT ON Favorite,
--       INSERT ON Subscription,
--       UPDATE ON Blog,
--       UPDATE ON Post,
--       UPDATE ON Comment,
--       DELETE ON Blog,
--       DELETE ON Post,
--       DELETE ON Comment,
--       DELETE ON Favorite,
--       DELETE ON Subscription
-- TO user;

-- GRANT CREATE SESSION,
--       SELECT ON Blog,
--       SELECT ON Post,
--       SELECT ON Comment
-- TO guest;